module.exports =[
    {
        username: 'theAnswer07',
        email: 'moisedia7@gmail.com',
        password: 'password',
        xboxUsername: 'theAnswer07',
        psnUsername: 'theAnswer07',
        steamUsername: 'theAnswer07',
        nintendoUsername: 'theAnswer07',
    },
    {
        username: 'Snufalufakis',
        email: 'snufalufakis@gmail.com',
        password: 'password',
        xboxUsername: 'Snufalufakis',
        psnUsername: 'Snufalufakis',
        steamUsername: 'Snufalufakis',
        nintendoUsername: 'Snufalufakis',
    },
    {
        username: 'VendettiStudios',
        email: 'daniel@vendettistudios.com',
        password: 'password',
        xboxUsername: 'VendettiStudios',
        psnUsername: 'VendettiStudios',
        steamUsername: 'VendettiStudios',
        nintendoUsername: 'VendettiStudios',
    },
    {
        username: 'JackJack',
        email: 'jackyoukstetter1@gmail.com',
        password: 'password',
        xboxUsername: 'JackJack',
        psnUsername: 'JackJack',
        steamUsername: 'JackJack',
        nintendoUsername: 'JackJack',
    },
    {
        username: 'jmonty94',
        email: 'jpmontgomery400@gmail.com',
        password: 'password',
        xboxUsername: 'YungLooony',
        psnUsername: 'jmonty94',
        steamUsername: 'jmonty94',
        nintendoUsername: 'jmonty94',
    },
]